openapi: 3.0.0
info:
  title: Movies API
  description: API documentation for the Movies and Series items.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
security:
  - ApiKey: []
paths:
  /directors:
    get:
      summary: Retrieve a list of directors
      responses:
        '200':
          description: Returns a list of all directors
  /genres:
    get:
      summary: List of genres
      responses:
        '200':
          description: list of genres
  /age-ratings:
    get:
      summary: List of age ratings
      responses:
        '200':
          description: list of age ratings
  /movies:
    get:
      summary: Retrieve a list of movies
      description: Returns a list of all movies in the database.
      parameters:
        - in: query
          name: genre
          schema:
            type: string
          required: false
          description: Genre to filter
        - in: query
          name: director
          schema:
            type: string
          required: false
          description: Director to filter
        - in: query
          name: age_rating
          schema:
            type: string
          required: false
          description: Age rating to filter
        - in: query
          name: id
          schema:
            type: string
          required: false
          description: ID to filter
        - in: query
          name: title
          schema:
            type: string
          required: false
          description: Title to filter
        - in: query
          name: synopsis
          schema:
            type: string
          required: false
          description: Synopsis to filter
      responses:
        '200':
          description: A JSON array of movies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'
  /series:
    get:
      summary: Retrieve a list of series
      parameters:
        - in: query
          name: genre
          schema:
            type: string
          required: false
          description: Genre to filter
        - in: query
          name: director
          schema:
            type: string
          required: false
          description: Genre to filter
      description: Returns a list of all series in the database.
      responses:
        '200':
          description: A JSON array of series
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Serie'
components:
  schemas:
    Movie:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
        synopsis:
          type: string
        year:
          type: integer
        release_date:
          type: string
          format: date
        duration_minutes:
          type: integer
        rating:
          type: number
          $ref: '#/components/schemas/AgeRating'
        director: 
          # object director defined below
          type: object
          $ref: '#/components/schemas/Director'
        genre:
          type: object
          $ref: '#/components/schemas/Genre'
      required:
        - title
        - synopsis
        - year
        - release_date
        - duration_minutes
        - rating
    Serie:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
    Director:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        birth_date:
          type: string
          format: date
        country:
          type: object
          $ref: '#/components/schemas/Country'
    AgeRating:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
    Genre:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        description:
          type: string
  securitySchemes:
    ApiKey: 
      type: apiKey
      in: header # can be "header", "query" or "cookie"
      name: X-API-KEY 